# DO NOT EDIT THIS FILE!
#
# Python module HelloApp generated by omniidl

import omniORB
omniORB.updateModule("HelloApp")

# ** 1. Stub files contributing to this module
import hello_idl

# ** 2. Sub-modules

# ** 3. End
