FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
COPY MQTT/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY MQTT/ /app/
CMD ["tail", "-f", "/dev/null"]