FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
COPY REST/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY REST/ /app/
EXPOSE 5151
CMD ["tail", "-f", "/dev/null"]